# Dados de conexão do banco H2
spring:
  datasource:
    url: jdbc:h2:mem:ffdb
    username: ffuser
    password: 123456

# Configuração do client web do banco H2
  h2:
    console:
      enabled: true
      path: /h2-console

# Configuração para mostrar o SQL no console

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true